### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by vsodre** [vsodre/flipg#3]
User management should cover the serve side of User entity. For the completion of this issue, is necessary to the following features be present:
- Login user
- Logout
- Register
- Edit profile

**Comment by nhipke** [comment]
I am working on modifying my code for mongodb

**Comment by nhipke** [comment]
account set up on mongolab

**Comment by vsodre** [comment]
@shadedpast this ticket have to wait until #2 be closed. Otherwise all work can be wasted.

**Comment by vsodre** [comment]
Laravel has user authentication built-in, I'll set it up.
